### DISCUSSION TITLE
JSON errors in HA

### DISCUSSION THREAD

**Discussion by jmerifjKriwe** [kalbasit/signal-api-receiver#67] [General]
Hi,

I installed this container and it works quite good. Nice work!

But I find errors in the log file which I would like to fix. And I have no idea to do this :-/

My sensor is:

```
  - platform: rest
    resource: !secret signal_rpc_url
    name: "Signal message received"
    json_attributes_path: envelope
    json_attributes:
      - source
      - sourceNumber
      - sourceUuid
      - sourceDevice
      - timestamp
    value_template: "{{ value_json.envelope.dataMessage.message }}"
```

In the log file I find a lot of:
- Empty reply found when expecting JSON data
- Template variable error: 'value_json' is undefined when rendering '{{ value_json.envelope.dataMessage.message }}'

Seems to appear if there is no message waiting - so 99,9% of the day.
So I understand why it is happing but it's flooding the log file (2690 entries in less than 24h). 

Thus I'm looking for an idea how to fix this :)

**Comment by leptoquark1** [comment]
This is rather an issue than discussion, since it's an response interface problem. 

I've addressed this issue in #52

**Reply by jmerifjKriwe** [reply]
Ok, great :-)

But this PR would only fix the "empty reply" issue. Not the one with "value_json is undefined", right?

**Reply by leptoquark1** [reply]
Yes

**Comment by jmerifjKriwe** [comment]
the "undefined" issue can be solved like this:

```
  - platform: rest
    resource: !secret signal_rpc_url
    name: "Signal message received"
    json_attributes_path: envelope
    json_attributes:
      - source
      - sourceNumber
      - sourceUuid
      - sourceDevice
      - timestamp
    value_template: >-
      {{ value_json.evenelope.dataMessage.message if
          value_json is defined and
          value_json.evenelope is defined and
          value_json.evenelope.dataMessage is defined and
          value_json.evenelope.dataMessage.message is defined else '' }}
```

It's necessary to have all the checks cause if you just check for value_json.evenelope.dataMessage.message it still will report "undefined". So have to check step by step.

**Comment by kalbasit** [comment]
I solved it myself in two parts. Following @jmerifjKriwe 's comment, I changed my sensor to read this

```yaml
- resource: "http://signal-api-receiver.nasreddine.svc.cluster.local:8105/receive/pop"
  sensor:
    - name: "Signal message received"
      value_template: >-
        {{ value_json['envelope']['dataMessage']['message'] if
          value_json is defined and
          'envelope' in value_json and
          'dataMessage' in value_json['envelope'] and
          'message' in value_json['envelope']['dataMessage'] else '' }}
      json_attributes_path: $.envelope
      json_attributes:
        - source
        - sourceNumber
        - sourceUuid
        - sourceDevice
        - timestamp
```

But I kept getting this in my logs

```
WARNING (MainThread) [homeassistant.components.rest.util] Empty reply found when expecting JSON data
```
For this, I followed the instructions for [Log filters](https://www.home-assistant.io/integrations/logger/#log-filters) and I added this to my configuration:

```yaml
logger:
  filters:
    homeassistant.components.rest.util:
      - "Empty reply found when expecting JSON data"

```
